Fix: Process conditional input booleans correctly
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/python-project-build/action.yaml b/.github/actions/python-project-build/action.yaml
--- a/.github/actions/python-project-build/action.yaml
+++ b/.github/actions/python-project-build/action.yaml
@@ -1,6 +1,6 @@
 ---
 # SPDX-License-Identifier: Apache-2.0
-# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>
+# SPDX-FileCopyrightText: 2024 The Linux Foundation
 
 name: "🧱 Python Build"
 description: "Builds a Python Project"
@@ -9,28 +9,24 @@ inputs:
   PURGE_OUTPUT_PATH:
     description: "Purge target artefact path prior to builds"
     required: false
-    default: false
+    default: "false"
   ARTEFACT_PATH:
     description: "Build artefacts will be output to this folder/directory"
     required: false
-    type: string
     default: "dist"
   BUILD_TAG:
     description: "Tag version/name for this specific build (semantic)"
     required: false
-    type: string
   GITHUB_ATTEST:
     # Attestations should not be used for development builds
     description: "Apply GitHub attestations to artefacts"
     required: false
-    type: boolean
-    default: false
+    default: "false"
   SIGSTORE_SIGN:
     # Signing should not be used for development builds
     description: "Sign build artefacts with Sigstore"
     required: false
-    type: boolean
-    default: false
+    default: "false"
 
 outputs:
   MATRIX_JSON:
@@ -75,7 +71,7 @@ runs:
     - name: "Patch project versioning metadata"
       if: env.python_project_version != inputs.build_tag
       # yamllint disable-line rule:line-length
-      uses: os-climate/osc-github-devops/.github/actions/python-project-version-patch@main
+      uses: os-climate/osc-github-devops/.github/actions/python-project-version-patch@c3c8c6ed8f61e21cef7bf2b4bfb08b8244c5dbc3 # 2025-01-14
       with:
         replacement_version: ${{ env.build_tag }}
 
@@ -100,22 +96,43 @@ runs:
         fi
 
         python -m pip install --disable-pip-version-check -q --upgrade pip
+
+        # PDM Build
         if [ -f pyproject.toml ]; then
           echo "Found file: pyproject.toml"
           echo "Building with command: pdm build --dest ${{ inputs.ARTEFACT_PATH }}"
-          pdm build --dest ${{ inputs.ARTEFACT_PATH }}
+          if (pdm build --dest ${{ inputs.ARTEFACT_PATH }}); then
+            echo "Build with PDM successful ✅"
+          else
+            echo "Build with PDM failed ❌"
+            exit 1
+          fi
+
+        # TOX Build
         elif [ -f tox.ini ]; then
           echo "Found TOX configuration file: tox.ini"
           echo "Attempting to install TOX..."
           python -m pip install --disable-pip-version-check -q --upgrade tox tox-gh-actions
           echo "Attempting build with: tox -e build"
           echo "WARNING: assumes build artefact path is valid"
-          tox -e build
+          if (tox -e build); then
+            echo "Build with TOX successful ✅"
+          else
+            echo "Build with TOX failed ❌"
+            exit 1
+          fi
+
+        # Build with Python module
         else
           echo "Neither file found: tox.ini/pyproject.toml"
           echo "Attempting build with: python -m build"
           python -m pip install --disable-pip-version-check -q --upgrade build
-          python -m build --outdir ${{ inputs.ARTEFACT_PATH }}
+          if (python -m build --outdir ${{ inputs.ARTEFACT_PATH }})
+            echo "Build with Python module successful ✅"
+          else
+            echo "Build with Python module failed ❌"
+            exit 1
+          fi
         fi
 
     - name: "Package dependency graph"
@@ -126,25 +143,25 @@ runs:
 
     - name: "Artefact attestation for: ${{ inputs.ARTEFACT_PATH }}"
       uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2.1.0
-      if: inputs.ATTEST
+      if: ${{ inputs.github_attest == 'true' }}
       with:
         subject-path: ${{ inputs.ARTEFACT_PATH }}/*
-
-    - name: "Validate artefacts with Twine"
-      # yamllint disable-line rule:line-length
-      uses: os-climate/osc-github-devops/.github/actions/python-twine-check@main
 
     # This step optional and must be explicitly requested (passed the relevant input)
     - name: "Sign packages with SigStore"
       # yamllint disable-line rule:line-length
       uses: sigstore/gh-action-sigstore-python@f514d46b907ebcd5bedc05145c03b69c1edd8b46 # v3.0.0
-      if: inputs.SIGSTORE_SIGN
+      if: ${{ inputs.sigstore_sign == 'true' }}
       env:
         package-path: ${{ inputs.ARTEFACT_PATH }}
       with:
         inputs: >-
           ./${{ inputs.ARTEFACT_PATH }}/*.tar.gz
           ./${{ inputs.ARTEFACT_PATH }}/*.whl
+
+    - name: "Validate artefacts with Twine"
+      # yamllint disable-line rule:line-length
+      uses: os-climate/osc-github-devops/.github/actions/python-twine-check@c3c8c6ed8f61e21cef7bf2b4bfb08b8244c5dbc3 # 2025-01-14
 
     - name: "Upload build artefacts"
       # yamllint disable-line rule:line-length
