Feat: Reconfigure testing to incorporate failures
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/python-project-test-matrix/action.yaml b/.github/actions/python-project-test-matrix/action.yaml
--- a/.github/actions/python-project-test-matrix/action.yaml
+++ b/.github/actions/python-project-test-matrix/action.yaml
@@ -8,13 +8,13 @@ description: "Test a Python Project, generate coverage report"
 
 inputs:
   # Mandatory
-  # A matrix Python build version should be passed as input
   PYTHON_VERSION:
+    # A matrix Python build version should be passed as input
     description: "Python version used to run test"
     required: true
     type: string
   # Optional
-  NEVER_FAIL:
+  PERMIT_TEST_FAIL:
     description: "Continue even when a test fails"
     required: false
     type: boolean
@@ -44,69 +44,77 @@ runs:
 
     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
+    - name: "Setup action/environment"
+      shell: bash
+      run: |
+        # Setup action/environment
+        if [ -n "${{ inputs.path_prefix }}" ] && [ ! -d "${{ inputs.path_prefix }}" ]; then
+          echo "Error: invalid path/prefix to project directory ❌"
+          exit 1
+        fi
+        if [ -n "${{ inputs.tests_path }}" ] && \
+          [ ! -d "${{ inputs.path_prefix }}${{ inputs.tests_path }}" ]; then
+          echo "Error: invalid path/prefix to test directory ❌"
+          echo "${{ inputs.path_prefix }}${{ inputs.tests_path }}"
+          exit 1
+        PERMIT_TEST_FAIL=$(echo ${{ inputs.PERMIT_TEST_FAIL }} |\
+        tr '[:upper:]' '[:lower:]')
+        if [ "f$PERMIT_TEST_FAIL" = "ftrue" ]; then
+          echo "Warning: test failures will be permitted ⚠️"
+          echo "PERMIT_TEST_FAIL=true" >> "$GITHUB_ENV"
+        fi
+
+        # Install modules required for testing
+        echo "Installing test tooling: pytest, pytest-cov ⬇️"
+        python -m pip install --disable-pip-version-check -q pytest pytest-cov
+        echo "Installing project dependencies ⬇️"
+        if [ -f ${{ inputs.path_prefix }}pyproject.toml ]; then
+          echo "Source: ${{ inputs.path_prefix }}pyproject.toml"
+          pip install -q ${{ inputs.path_prefix }}pyproject.toml
+        fi
+        if [ -f ${{ inputs.path_prefix }}requirements.txt ]; then
+          echo "Source: requirements.txt"
+          pip install -q -r ${{ inputs.path_prefix }}requirements.txt
+        fi
+        if [ -z "${{ inputs.python_version }}" ]; then
+          echo "Error: Python version was not provided ❌"
+          exit 1
+        else
+          echo "Using Python: "${{ inputs.python_version }} 🐍"
+        fi
+
     - name: "Set up Python ${{ inputs.python_version }}"
       # yamllint disable-line rule:line-length
       uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
       with:
         python-version: ${{ inputs.python_version }}
 
-    - name: "Install test dependencies"
-      id: install-dependencies
-      shell: bash
-      run: |
-        # Install test dependencies
-        echo "Upgrading: pip"
-        python -m pip install -q --upgrade pip
-        echo "Installing: pytest, pytest-cov"
-        python -m pip install --disable-pip-version-check -q pytest pytest-cov
-        if [ -f pyproject.toml ]; then
-          echo "Installing dependencies from: pyproject.toml"
-          pip install -q .
-        fi
-        if [ -f requirements.txt ]; then
-          echo "Installing dependencies from: requirements.txt"
-          pip install -q -r requirements.txt
-        fi
-
-    # ToDo: Run tests with TOX
-    # Detect tox.ini
+    # ToDo: Implement test using TOX
+    # Check for presence of tox.ini
     # Parse file for test stanza
     # Use tox if configured for tests
     # Otherwise proceed to regular method (pytest)
 
-    - name: "Setup failure handling"
-      shell: bash
-      run: |
-        # Setup failure handling
-        NEVER_FAIL=$(echo ${{ inputs.NEVER_FAIL }} |\
-        tr '[:upper:]' '[:lower:]')
-        if [ "f$NEVER_FAIL" = "ftrue" ]; then
-          echo "never_fail=true" >> "$GITHUB_ENV"
-        fi
-
     - name: "Run tests and generate coverage report [NEVER FAIL]"
-      if: ${{ env.NEVER_FAIL }} == 'true'
+      if: ${{ env.PERMIT_TEST_FAIL }} == 'true'
       shell: bash
       run: |
-        # Run tests and generate coverage report
-        if [ -d "${{ inputs.path_prefix }}${{ inputs.tests_path }}" ]; then
-          echo "Test path: ${{ inputs.path_prefix }}${{ inputs.tests_path }}"
-          pytest --cov --cov-report=html:coverage_report \
-            "${{ inputs.path_prefix }}${{ inputs.tests_path }}" || true
-        elif [ -d ${{ inputs.path_prefix }}tests ]; then
-          echo "Test path: tests"
-          pytest --cov --cov-report=html:coverage_report \
-            "${{ inputs.path_prefix }}tests" || true
-        elif [ -d ${{ inputs.path_prefix }}test ]; then
-          echo "Test path: test"
-          pytest --cov --cov-report=html:coverage_report \
-            "${{ inputs.path_prefix }}test" || true
+        # Test folder has been specified
+        if [ -n "${{ inputs.tests_path }}" ]; then
+          TEST_PATH="${{ inputs.path_prefix }}${{ inputs.tests_path }}"
+        # Otherwise use common locations
+        elif [ -d "${{ inputs.path_prefix }}tests" ]; then
+          TEST_PATH="${{ inputs.path_prefix }}tests"
+        elif [ -d "${{ inputs.path_prefix }}test" ]; then
+          TEST_PATH="${{ inputs.path_prefix }}test"
         else
-          echo "Error: path to tests could not be located ❌"
+          echo "Error: no valid test path was found ❌"
+          exit 1
         fi
+        pytest --cov --cov-report=html:coverage_report "$TEST_PATH" || true
 
     - name: "Run tests and generate coverage report [WILL FAIL]"
-      if: ${{ env.NEVER_FAIL }} != 'true'
+      if: ${{ env.PERMIT_TEST_FAIL }} != 'true'
       shell: bash
       run: |
         # Run tests and generate coverage report
@@ -126,6 +134,7 @@ runs:
           echo "Error: path to tests could not be located ❌"
           exit 1
         fi
+
     - name: "Create ZIP archive of coverage report"
       shell: bash
       run: |
