Feat: Add optional inputs to matrix jobs
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/python-project-test-matrix/action.yaml b/.github/actions/python-project-test-matrix/action.yaml
--- a/.github/actions/python-project-test-matrix/action.yaml
+++ b/.github/actions/python-project-test-matrix/action.yaml
@@ -3,27 +3,45 @@
 # SPDX-FileCopyrightText: 2025 The Linux Foundation
 
 # python-project-test-matrix
-name: "🧪 Python Tests"
-description: "Tests a Python Project and generates coverage reports"
+name: "🧪 Python Test"
+description: "Test a Python Project, generate coverage report"
 
 inputs:
-  # The matrix Python build version should be passed into this action
+  # Mandatory
+  # A matrix Python build version should be passed as input
   PYTHON_VERSION:
-    description: "Python version used to build artefacts"
+    description: "Python version used to run test"
     required: true
+    type: string
+  # Optional
   NEVER_FAIL:
     description: "Continue even when a test fails"
     required: false
+    type: boolean
     default: false
   REPORT_ARTEFACT:
     description: "Store test/coverage report as artefact"
     required: false
+    type: boolean
     default: false
+  TESTS_PATH:
+    description: "Folder containing Python tests"
+    required: false
+    type: string
+  PATH_PREFIX:
+    description: "Directory location containing project code"
+    type: string
+    required: false
+    default: ""
 
 runs:
   using: "composite"
   steps:
-    # yamllint disable-line rule:line-length
+    # Harden the runner used by this workflow
+    - uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
+      with:
+        egress-policy: audit
+
     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
     - name: "Set up Python ${{ inputs.python_version }}"
@@ -40,7 +58,7 @@ runs:
         echo "Upgrading: pip"
         python -m pip install -q --upgrade pip
         echo "Installing: pytest, pytest-cov"
-        pip install -q pytest pytest-cov
+        python -m pip install --disable-pip-version-check -q pytest pytest-cov
         if [ -f pyproject.toml ]; then
           echo "Installing dependencies from: pyproject.toml"
           pip install -q .
@@ -50,60 +68,55 @@ runs:
           pip install -q -r requirements.txt
         fi
 
-    # Add additional workflow test steps here:
-    # 1. detect tox.ini
-    # 2. parse file for test stanza
-    # 3. use tox if testing available there
-    # 4. exit 0 if successful (following steps will be skipped)
-    # 5. otherwise proceed to fallback method below (pytest)
+    # ToDo: Run tests with TOX
+    # Detect tox.ini
+    # Parse file for test stanza
+    # Use tox if configured for tests
+    # Otherwise proceed to regular method (pytest)
 
-    - name: "Run tests and coverage report"
+    - name: "Run tests, generate coverage report"
       id: run-tests
-      if: inputs.NEVER_FAIL == 'false'
       shell: bash
       run: |
-        # Run tests, coverage report
-        if [ -d test ]; then
-          pytest --cov --cov-report=html:coverage_report tests
+        # Run tests, generate coverage report
+        NEVER_FAIL=$(echo ${{ inputs.NEVER_FAIL }} |\
+        tr '[:upper:]' '[:lower:]')
+        if [ -d "${{ inputs.tests_path }}" ]; then
+          pytest --cov --cov-report=html:coverage_report \
+            "${{ inputs.path_prefix }}${{ inputs.tests_path }}"
         elif [ -d tests ]; then
-          pytest --cov --cov-report=html:coverage_report tests
+          pytest --cov --cov-report=html:coverage_report \
+            "${{ inputs.path_prefix }}tests"
+        elif [ -d test ]; then
+          pytest --cov --cov-report=html:coverage_report \
+            "${{ inputs.path_prefix }}test"
         else
-          echo "No test/tests directories were found"
-          echo "Aborting testing without error"; exit 0
-        fi
-
-    - name: "Run tests and coverage report [NEVER_FAIL]"
-      id: run-tests-nofail
-      if: inputs.REPORT_ARTEFACT == 'true'
-      shell: bash
-      run: |
-        # Run tests, coverage report
-        if [ -d test ]; then
-          pytest --cov --cov-report=html:coverage_report tests || true
-        elif [ -d tests ]; then
-          pytest --cov --cov-report=html:coverage_report tests || true
-        else
-          echo "No test/tests directories were found"
-          echo "Aborting testing without error"; exit 0
+          echo "Error: path to tests could not be located ❌"
+          if [ "f$NEVER_FAIL" != "ftrue" ]; then
+            exit 1
+          fi
         fi
 
     - name: "Create ZIP archive of coverage report"
-      id: archive-report
-      if: inputs.REPORT_ARTEFACT == 'true'
       shell: bash
       run: |
         # Create ZIP archive of coverage report
-        if [ -d coverage_report ]; then
-          echo "Creating ZIP file of HTML coverage report"
-          zip -r test_coverage_report-${{ inputs.PYTHON_VERSION }}.zip coverage_report
-        else
-          echo "No coverage report directory exists"
+        REPORT_ARTEFACT=$(echo ${{ inputs.REPORT_ARTEFACT }} |\
+        tr '[:upper:]' '[:lower:]')
+        if [ "f$REPORT_ARTEFACT" = "ftrue" ]; then
+          if [ -d coverage_report ]; then
+            echo "Creating ZIP file of HTML coverage report"
+            zip -r test_coverage_report-${{ inputs.python_version }}.zip coverage_report
+          else
+            echo "No coverage report directory exists"
+          fi
         fi
+        echo "report_artefact=$REPORT_ARTEFACT" >> "$GITHUB_ENV"
 
     - name: "Upload test/coverage report"
       uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
-      if: inputs.REPORT_ARTEFACT == 'true'
+      if: env.REPORT_ARTEFACT == 'true'
       with:
-        name: test_coverage_report-${{ inputs.PYTHON_VERSION }}.zip
-        path: test_coverage_report-${{ inputs.PYTHON_VERSION }}.zip
+        name: test_coverage_report-${{ inputs.python_version }}.zip
+        path: test_coverage_report-${{ inputs.python_version }}.zip
         retention-days: 90
