Feat: Better python-twine-check-action validation (#746)
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>
Signed-off-by: Modeseven Industrial Solutions <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/python-twine-check-action/action.yaml b/.github/actions/python-twine-check-action/action.yaml
--- a/.github/actions/python-twine-check-action/action.yaml
+++ b/.github/actions/python-twine-check-action/action.yaml
@@ -22,14 +22,33 @@ runs:
       shell: bash
       run: |
         # Verify Python build artefacts with Twine
+        ARTEFACT_PATH="${{ inputs.path }}"
+        if [ -z "$ARTEFACT_PATH" ]; then
+          echo "Error: mandatory input PATH was not set/configured ❌"
+          exit 1
+        fi
+
+        if (ls "$ARTEFACT_PATH"); then
+          ARTEFACTS=$(ls dist | wc -l)
+          if [ "$ARTEFACTS" -eq 0 ]; then
+            echo "Error: specified directory/path was empty ❌"
+            exit 1
+          else
+            echo "Files in specified directory/path: $ARTEFACTS"
+          fi
+        else
+          echo "Error: specified directory/path does not exist ❌"
+          exit 1
+        fi
+
         if [ -z ${{ inputs.path }} ]; then
           echo "Error: mandatory PATH input was not set/configured ❌"
           exit 1
         fi
         echo -n "Installing: twine"
         pip install --disable-pip-version-check -q --upgrade twine
-        echo "Running: twine check ${{ inputs.path }}/*"
-        if (twine check ${{ inputs.path }}/*); then
+        echo "Running: twine check $ARTEFACT_PATH/*"
+        if (twine check $ARTEFACT_PATH/*); then
           echo "Verified Python build artefacts with Twine ✅"
           echo "Verified Python build artefacts with Twine ✅" \
             >> "$GITHUB_STEP_SUMMARY"
