Feat: Align project version/name extraction (#76)
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/python-project-version/action.yaml b/.github/actions/python-project-version/action.yaml
--- a/.github/actions/python-project-version/action.yaml
+++ b/.github/actions/python-project-version/action.yaml
@@ -2,11 +2,11 @@
 # SPDX-License-Identifier: Apache-2.0
 # SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>
 
-name: "🐍 Get Python Project Versioning"
+name: "🐍 Get Python Project Version"
 description: "Returns the version of the Python Project"
 
 outputs:
-  PROJECT_VERSION:
+  PYTHON_PROJECT_VERSION:
     description: "The version of the Python project from pyproject.toml or setup.py"
     value: ${{ steps.variables.outputs.python_project_name }}
 
@@ -23,7 +23,7 @@ runs:
       with:
         check_path: "pyproject.toml"
 
-    - name: "Use project name from setup.py"
+    - name: "Use project version from setup.py"
       if: steps.setup-py.outputs.type == 'file'
       uses: os-climate/osc-github-devops/.github/actions/file-grep-regex@main
       with:
@@ -32,7 +32,7 @@ runs:
         regex: '(?<=version=")([^"]*)'
         filename: "setup.py"
 
-    - name: "Use project name from pyproject.toml"
+    - name: "Use project version from pyproject.toml"
       if: steps.pyproject-toml.outputs.type == 'file'
       uses: os-climate/osc-github-devops/.github/actions/file-grep-regex@main
       with:
@@ -55,9 +55,23 @@ runs:
       run: |
         # Return extracted values
 
+        # pyproject.toml is preferred source if both files exist
+        if [ ${{ steps.pyproject-toml.outputs.type == 'file' }} ]; then
+          echo "Using project version from source: pyproject.toml"
+          PYTHON_PROJECT_VERSION="${{ steps.pyproject-toml-name.outputs.extracted_string}}"
+
+        elif [ ${{ steps.setup-py.outputs.type == 'file' }} ]; then
+          echo "Using project version from source: setup.py"
+          PYTHON_PROJECT_VERSION="${{ steps.setup-py-name.outputs.extracted_string}}"
+        fi
+
+        if [ -z "$PYTHON_PROJECT_VERSION" ]; then
+          echo "The project name extraction failed ❌"; exit 1
+        fi
+
         PYTHON_PROJECT_VERSION="${{ env.extracted_string}}"
-        echo "PYTHON_PROJECT_VERSION: $PYTHON_PROJECT_VERSION"
+        echo "python_project_version: $PYTHON_PROJECT_VERSION ✅"
 
         # Make available to the GitHub environment
-        echo "project_version=$PYTHON_PROJECT_VERSION" >> "$GITHUB_ENV"
-        echo "python_version=$PYTHON_PROJECT_VERSION" >> "$GITHUB_OUTPUT"
+        echo "python_project_version=$PYTHON_PROJECT_VERSION" >> "$GITHUB_ENV"
+        echo "python_project_version=$PYTHON_PROJECT_VERSION" >> "$GITHUB_OUTPUT"
