Fix: Pass build version in repository.yaml to github-release.yaml
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/file-sed-regex/action.yaml b/.github/actions/file-sed-regex/action.yaml
--- a/.github/actions/file-sed-regex/action.yaml
+++ b/.github/actions/file-sed-regex/action.yaml
@@ -60,6 +60,11 @@ runs:
         echo "Regular expression to use: $REGEX"
         echo "File to search: $FILENAME"
 
-        sed "$FLAGS" '${{ inputs.REGEX }}' "$FILENAME"
+        if (sed "$FLAGS" '${{ inputs.REGEX }}' "$FILENAME"); then
+          echo "sed command was successful ✅ "
+        else
+          echo "sed command exit status: $?"
+          echo "sed command failed ❌"
+        fi
 
         #SHELLCODEEND
