Chore: Update workflows
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/gerrit-issue-id-action/action.yaml b/.github/actions/gerrit-issue-id-action/action.yaml
--- a/.github/actions/gerrit-issue-id-action/action.yaml
+++ b/.github/actions/gerrit-issue-id-action/action.yaml
@@ -43,29 +43,20 @@ runs:
       id: lookup
       shell: bash
       run: |
-        set -vx
-
         # Look up appropriate JIRA ticket for this change
         echo "Looking up appropriate JIRA ticket for this change"
         ACTOR="${{ github.actor }}"
         ACTOR_ID="${{ github.actor_id }}"
         echo "Actor: $ACTOR [$ACTOR_ID]"
 
-        # Validate lookup table contents
-        ISSUE_ID_LOOKUP_JSON='${{ inputs.ISSUE_ID_LOOKUP_JSON }}'
+        # Check lookup table variable
         if [ -z "${{ inputs.ISSUE_ID_LOOKUP_JSON }}" ]; then
-          echo "The required lookup JSON/variable is not set: ISSUE_ID_LOOKUP_JSON"; exit 1
-        else
-          echo "Lookup table:"
-          echo "$ISSUE_ID_LOOKUP_JSON"
+          echo "The required lookup variable/JSON is not set: ISSUE_ID_LOOKUP_JSON"; exit 1
         fi
 
         JQ=$(which jq || true)
         if [ -x "$JQ" ]; then
           KEY="$ACTOR"
-          echo '${{ inputs.ISSUE_ID_LOOKUP_JSON }}' > table.json
-          echo "File contents:"
-          cat table.json
           # yamllint disable-line rule:line-length
           VALUE=$(echo '${{ inputs.ISSUE_ID_LOOKUP_JSON }}' | jq -r --arg KEY "$KEY" '.[] | select(.key==$KEY) | .value')
           if [ -z "$VALUE" ]; then
