Chore: Update workflows (#226)
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/gerrit-issue-id-action/action.yaml b/.github/actions/gerrit-issue-id-action/action.yaml
--- a/.github/actions/gerrit-issue-id-action/action.yaml
+++ b/.github/actions/gerrit-issue-id-action/action.yaml
@@ -50,10 +50,10 @@ runs:
         echo "Actor: $ACTOR [$ACTOR_ID]"
 
         # Validate lookup table contents
-        # ISSUE_ID_LOOKUP_JSON="${{ inputs.ISSUE_ID_LOOKUP_JSON }}"
-        ISSUE_ID_LOOKUP_JSON="${{ fromJson(inputs.ISSUE_ID_LOOKUP_JSON) }}"
+        ISSUE_ID_LOOKUP_JSON="${{ inputs.ISSUE_ID_LOOKUP_JSON }}"
+        # ISSUE_ID_LOOKUP_JSON="${{ fromJson(inputs.ISSUE_ID_LOOKUP_JSON) }}"
         if [ -z "${{ inputs.ISSUE_ID_LOOKUP_JSON }}" ]; then
-          echo "The lookup table variable was not accessible/set: ISSUE_ID_LOOKUP_JSON"; exit 1
+          echo "The required lookup JSON/variable is not set: ISSUE_ID_LOOKUP_JSON"; exit 1
         else
           echo "Lookup table:"
           echo "$ISSUE_ID_LOOKUP_JSON"
