Chore: Tidy up tests/resources folder
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/python-versioning-patch/action.yaml b/.github/actions/python-versioning-patch/action.yaml
--- a/.github/actions/python-versioning-patch/action.yaml
+++ b/.github/actions/python-versioning-patch/action.yaml
@@ -5,20 +5,19 @@
 name: "🐍 Patch Python Project Metadata/Version"
 
 inputs:
-  CURRENT:
-    description: "Current version to replace"
-    required: true
-    type: string
-  TARGET:
-    description: "Target/replacement version"
+  STRING:
+    description: "New version string"
     required: true
     type: string
 
 runs:
   using: "composite"
   steps:
-    - id: patch-pyproject-toml
-      name: "Substituting project version string"
+    - name:
+      id: update-version
+      uses: os-climate/osc-github-devops/.github/actions/file-sed-regex@main
+
+    - name: "Substituting project version string"
       shell: bash
       run: |
         # Substituting project version string
@@ -30,27 +29,26 @@ runs:
           echo "Running from a shell, NOT workflow"
           export GITHUB_OUTPUT="/dev/null"
           export GITHUB_ENV="/dev/null"
-          if [ $# -ne 2 ]; then
+          if [ $# -ne 1 ]; then
             echo "Error: invalid arguments specified"
-            echo "Usage:  $0 [current-tag] [target-tag]"; exit 1
+            echo "Usage:  $0 [string]"; exit 1
           else
-            CURRENT="$1"
-            TARGET="$2"
+            STRING="$1"
           fi
         else
-          CURRENT=${{ inputs.CURRENT }}
-          TARGET=${{ inputs.TARGET }}
+          STRING=${{ inputs.STRING }}
         fi
 
-        echo "Search for: $CURRENT  Replace with: $TARGET"
-
-        if [ -z "$CURRENT" ] || [ -z "$TARGET" ]; then
-          echo "Error: one or more required inputs NOT received"
+        if [ -z "$STRING" ]; then
+          echo "Error: string input was NOT received"
           echo "Check the calling workflow syntax and setup..."; exit 1
         fi
+        echo "New version string to insert: $STRING"
 
         # Attempt version string substitution for project
         sed -i -E "s:^version =.*$:version = \"$TARGET\":" pyproject.toml
+
+
 
         # Check to see if the above succeeded
         if !(grep -q "version = \"$TARGET\"" pyproject.toml); then
@@ -58,3 +56,13 @@ runs:
         fi
 
         #SHELLCODEEND
+
+    - name: "Substituting project version string"
+      shell: bash
+      run: |
+        # Validate file was updated
+
+        # Check to see if the above succeeded
+        if !(grep -q "version = \"$TARGET\"" pyproject.toml); then
+          echo "Error: failed version substitution in pyproject.toml"; exit 1
+        fi
diff --git a/.github/workflows/actions.yaml b/.github/workflows/actions.yaml
--- a/.github/workflows/actions.yaml
+++ b/.github/workflows/actions.yaml
@@ -355,34 +355,54 @@ jobs:
           echo 'String comparison/action logic appears to be broken'
           exit 1
 
-      - name: "Test TOX stanza [specific/individual stanza]"
-        id: tox-stanza-test-individual
+      # Action: path-check
+      - name: "Action: path test [valid file]"
+        id: path-check-file
         # yamllint disable-line rule:line-length
-        uses: os-climate/osc-github-devops/.github/actions/string-in-multiline-text@main
+        uses: os-climate/osc-github-devops/.github/actions/path-check@main
         with:
-          string: "testenv:tests"
-          encoded_text: "${{ steps.tox-stanza.outputs.encoded_stanza }}"
-          substring_match: "false"
-          case_insensitive: "false"
+          check_path: "tests/resources/test-file"
 
-      - name: "Test TOX stanza [multiple matches]"
-        id: tox-stanza-test-multiple
+      - name: "Action: path test [valid folder]"
+        id: path-check-folder
         # yamllint disable-line rule:line-length
-        uses: os-climate/osc-github-devops/.github/actions/string-in-multiline-text@main
+        uses: os-climate/osc-github-devops/.github/actions/path-check@main
         with:
-          string: "testenv:"
-          encoded_text: "${{ steps.tox-stanza.outputs.encoded_stanza }}"
-          substring_match: "true"
-          case_insensitive: "false"
+          check_path: "tests/resources/test-folder"
 
-      - name: "Report Errors in TOX stanza tests"
+      - name: "Action: path test [valid symlink to file]"
+        id: path-check-symlink-file
         # yamllint disable-line rule:line-length
-        if: (steps.tox-stanza-test-individual.outputs.match == 'false' ||
-          steps.tox-stanza-test-individual.outputs.count != '1') ||
-          (steps.tox-stanza-test-multiple.outputs.match == 'false' ||
-          steps.tox-stanza-test-multiple.outputs.count != '5')
+        uses: os-climate/osc-github-devops/.github/actions/path-check@main
+        with:
+          check_path: "tests/resources/test-valid-file-symlink"
+
+      - name: "Action: path test [valid symlink to folder]"
+        id: path-check-symlink-folder
+        # yamllint disable-line rule:line-length
+        uses: os-climate/osc-github-devops/.github/actions/path-check@main
+        with:
+          check_path: "tests/resources/test-valid-folder-symlink"
+
+      - name: "Action: path test [invalid symlink]"
+        id: path-check-invalid-symlink
+        # yamllint disable-line rule:line-length
+        uses: os-climate/osc-github-devops/.github/actions/path-check@main
+        with:
+          check_path: "tests/resources/test-invalid-symlink"
+
+      # Tests: path-check
+      - name: "Error with path tests (files/folders/symlinks)"
+        id: path-check-errors
         shell: bash
+        if: steps.path-check-file.outputs.type != 'file' ||
+          steps.path-check-file.outputs.symlink != 'false' ||
+          steps.path-check-folder.outputs.type != 'folder' ||
+          steps.path-check-folder.outputs.symlink != 'false' ||
+          steps.path-check-symlink-file.outputs.type != 'file' ||
+          steps.path-check-symlink-file.outputs.symlink != 'true' ||
+          steps.path-check-invalid-symlink.outputs.type != 'invalid' ||
+          steps.path-check-invalid-symlink.outputs.symlink != 'true'
         run: |
-          # Check string-comparison action logic
-          echo 'Parsing of TOX stanza appears to be broken'
-          exit 1
+          # Report errors with path tests
+          echo "One or more path checks failed validation"; exit 1
