chore: Remove unnecessary dependencies step, make optional
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/standalone-linting-action/action.yaml b/.github/actions/standalone-linting-action/action.yaml
--- a/.github/actions/standalone-linting-action/action.yaml
+++ b/.github/actions/standalone-linting-action/action.yaml
@@ -14,34 +14,34 @@ inputs:
     # yamllint disable-line rule:line-length
     default: "https://raw.githubusercontent.com/lfit/releng-reusable-workflows/refs/heads/main/.github/actions/standalone-linting-action/pre-commit-config.yaml"
   DEPENDENCIES_URL:
-    description: "Download location for Python dependencies"
+    description: "Download location for additional Python dependencies"
     type: string
     required: false
-    # yamllint disable-line rule:line-length
-    default: "https://raw.githubusercontent.com/os-climate/osc-github-devops/refs/heads/main/.github/actions/standalone-linting-action/requirements.txt"
-  FORCE_REMOTE:
+  REMOTE_CONFIG:
     description: "Ignore local linting configuration; always install from remote"
     type: string
     required: false
-    default: "false"
-
-#
-env:
-  python-version: "3.12"
+    default: "true"
+  PYTHON-VERSION:
+    description: "Python version used to run pre-commit hooks"
+    type: string
+    required: false
+    # Needs to be maintained; best practice is pass explicitly to setup-python
+    default: "3.12"
 
 runs:
   using: "composite"
   steps:
+    - name: "Checkout repository"
+      # yamllint disable-line rule:line-length
+      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+
     - name: "Setup Python"
       # yamllint disable-line rule:line-length
       uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
       with:
-        python-version: ${{ env.python-version }}
+        python-version: ${{ inputs.python-version }}
         cache: "pip"
-
-    - name: "Checkout repository"
-      # yamllint disable-line rule:line-length
-      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
     - name: "Install pre-commit, check prerequisites"
       shell: bash
@@ -54,7 +54,7 @@ runs:
         fi
 
     - name: "Check for local linting configuration"
-      if: inputs.force_remote != 'true'
+      if: inputs.REMOTE_CONFIG != 'true'
       id: local-precommit-config
       # yamllint disable-line rule:line-length
       uses: lfit/releng-reusable-workflows/.github/actions/path-check-action@473a3c654d58fa0c27f91a9cc25bd9433de43d5e # v0.2.4
@@ -63,7 +63,7 @@ runs:
 
     - name: "Download remote pre-commit configuration"
       # yamllint disable-line rule:line-length
-      if: steps.local-precommit-config.outputs != 'file' || inputs.force_remote == 'true'
+      if: steps.local-precommit-config.outputs != 'file' || inputs.REMOTE_CONFIG == 'true'
       shell: bash
       run: |
         # Download remote pre-commit configuration
@@ -73,18 +73,20 @@ runs:
         curl -sS -o .pre-commit-config.yaml "${{ inputs.CONFIG_URL }}"
         echo "Pre-commit configuration file downloaded ✅"
 
-    #    - name: "Download/install Python dependencies"
-    #      # yamllint disable-line rule:line-length
-    #      shell: bash
-    #      if: steps.local-precommit-config.outputs != 'file' || inputs.force_remote == 'true'
-    #      run: |
-    #        # Download Python dependencies file
-    #        echo "Downloading configuration from:"
-    #        echo "${{ inputs.DEPENDENCIES_URL }}"
-    #        curl -sS -o /tmp/requirements.txt "${{ inputs.DEPENDENCIES_URL }}"
-    #        echo "Python dependencies file downloaded ✅"
-    #        echo "Installing Python dependencies and pre-commit"
-    #        pip install --disable-pip-version-check --upgrade -r /tmp/requirements.txt
+    - name: "Install additional Python dependencies"
+      if: inputs.DEPENDENCIES_URL != ''
+      shell: bash
+      run: |
+        # Install additional Python dependencies
+        echo "Downloading configuration from:"
+        echo "${{ inputs.DEPENDENCIES_URL }}"
+        if (curl -sS -o /tmp/requirements.txt "${{ inputs.DEPENDENCIES_URL }}"); then
+          echo "Python dependencies file downloaded ✅"
+        else
+          echo "Error: unable to download dependencies ❌"; exit 1
+        fi
+        echo "Installing additional Python dependencies"
+        pip install --disable-pip-version-check --upgrade -r /tmp/requirements.txt
 
     - name: "Validate configuration"
       shell: bash
