Test: Try and get GitHub release working with token (#617)
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/github-release-action/action.yaml b/.github/actions/github-release-action/action.yaml
--- a/.github/actions/github-release-action/action.yaml
+++ b/.github/actions/github-release-action/action.yaml
@@ -72,15 +72,23 @@ runs:
       with:
         tag: ${{ inputs.tag }}
 
-    - name: "Report build tag, setup ENV"
+    - name: "Check action environment"
       shell: bash
       run: |
+        # Check action environment
+        if [ -z "${{ inputs.token }}" ]; then
+          echo "Error: token must be passed as input to composite action 🛑"
+          echo "Error: token must be passed as input to composite action 🛑" \
+            >> "$GITHUB_STEP_SUMMARY"
+          exit 1
+        fi
         # Build tag values
         if [ ${{ steps.tag-validate.outputs.semantic }} == 'true' ]; then
           pushed_tag="${{ inputs.tag }}"
         else
           echo "Release tag NOT semantic: ${{ inputs.tag }} ❌"
-          echo "Release tag NOT semantic: ${{ inputs.tag }} ❌" >> "$GITHUB_STEP_SUMMARY"
+          echo "Release tag NOT semantic: ${{ inputs.tag }} ❌" \
+            >> "$GITHUB_STEP_SUMMARY"
           exit 1
         fi
         if [ -z "${{ inputs.PROJECT_NAME }}" ]; then
@@ -124,6 +132,8 @@ runs:
       if: inputs.artefact_location != '' && inputs.GH_RELEASE_DISABLE == 'false'
       # Note: a bug in release v2.2.0 causes upload failures
       uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
+      env:
+        GITHUB_TOKEN: ${{ inputs.token }}
       with:
         token: ${{ inputs.token }}
         prerelease: ${{ inputs.prerelease }}
@@ -139,6 +149,8 @@ runs:
       if: inputs.artefact_location == '' && inputs.GH_RELEASE_DISABLE == 'false'
       # Note: a bug in release v2.2.0 causes upload failures
       uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
+      env:
+        GITHUB_TOKEN: ${{ inputs.token }}
       with:
         token: ${{ inputs.token }}
         prerelease: ${{ inputs.prerelease }}
