Feat: Full implementation of github-list-releases-action
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/github-list-releases-action/action.yaml b/.github/actions/github-list-releases-action/action.yaml
--- a/.github/actions/github-list-releases-action/action.yaml
+++ b/.github/actions/github-list-releases-action/action.yaml
@@ -5,38 +5,132 @@
 # github-list-releases-action
 name: "📦 List GitHub Releases"
 description: "Returns a list of releases for the current repository"
+# Return limited to 1000 records due to API query limits
+# ToDo: add support for API query pagination
+# 640K ought to be enough for anybody
 
 inputs:
   # Optional
   TAG:
-    description: "When supplied, checks if release is present"
+    description: "Check if this tag/version has been released"
     required: false
     type: string
-  DISPLAY_IN_SUMMARY:
+  SUMMARY_OUTPUT:
     description: "Displays list in summary output"
     required: false
     default: "false"
     type: string
-  INCLUDE_PRE_RELEASES:
-    description: "Includes pre-release builds in output"
+  PRODUCTION_ONLY:
+    description: "Includes pre-release and draft releases in output"
     required: false
     default: "false"
     type: string
+  RETURN_TYPE:
+    description: "Set to either: text|json"
+    required: false
+    default: "text"
+    type: string
+  JSON_FIELDS:
+    description: "Fields to return when return type set to JSON"
+    required: false
+    default: "tagName"
+    type: string
+  ORDER:
+    description: "Sort order: asc|desc"
+    required: false
+    default: "desc"
+    type: string
+
 outputs:
   # Optional
-  RELEASED:
-    description: "Set true if a provided tag/version has been released"
-    value: ${{ steps.process.outputs.released }}
+  MATCH:
+    description: "Has provided tag/version already been released"
+    type: string
 
 runs:
   using: "composite"
   steps:
-    - name: "Placeholder output"
-      id: process
+    - name: "List GitHub Releases"
+      id: releases
       shell: bash
       run: |
-        # Placeholder output
-        echo "# Placeholder for: 📦 List GitHub Releases"
-        echo "# Placeholder for: 📦 List GitHub Releases" >> "$GITHUB_STEP_SUMMARY"
-        echo "released=false" >> "$GITHUB_ENV"
-        echo "released=false" >> "$GITHUB_OUTPUT"
+        # List GitHub Releases
+
+        # Check GitHub CLI is available
+        GH_CLI=$(which gh)
+        if [ ! -x GH_CLI ]; then
+          echo "Error: GitHub CLI was NOT found in PATH ❌"
+          exit 1
+        fi
+
+        # Function to check releases
+        checkReleases() {
+          while IFS= read -r RELEASE ; do
+          if [ "$RELEASE" = "$TAG" ]; then
+            MATCH="true"
+          fi
+          done <<< "$RELEASE_OUTPUT"
+        }
+
+        # Case-insensitive matching of inputs
+        SUMMARY_OUTPUT=$(echo ${{ inputs.summary_output }} | tr '[:upper:]' '[:lower:]')
+        PRODUCTION_ONLY=$(echo ${{ inputs.PRODUCTION_ONLY }} | tr '[:upper:]' '[:lower:]')
+        RETURN_TYPE=$(echo ${{ inputs.return_type }} | tr '[:upper:]' '[:lower:]')
+        ORDER=$(echo ${{ inputs.order }} | tr '[:upper:]' '[:lower:]')
+        TAG="${{ inputs.tag }}"
+
+        # Set baseline flags for the CLI command
+        # Note: limit MUST be provided numerically to GH CLI
+        CLI_FLAGS="release list  --limit 1000 -O ${{ inputs.ORDER }} --limit 1000"
+
+        if [ "f$PRODUCTION_ONLY" = "ffalse" ]; then
+          CLI_FLAGS="$CLI_FLAGS --exclude-drafts --exclude-pre-releases"
+        fi
+
+        # Check dependent input parameters are coherent
+        if [ "$RETURN_TYPE" = "json" ] && [ -z  "$JSON_FIELDS" ]; then
+          echo "Error: when return type is JSON fields MUST be specified ❌"
+          exit 1
+        elif [ "$RETURN_TYPE" = "json" ]; then
+          CLI_FLAGS="$CLI_FLAGS --json ${{ inputs.JSON_FIELDS }}"
+        fi
+
+        echo "# 📦 GitHub Releases"
+        if [ "f$SUMMARY_OUTPUT" = "ftrue" ]; then
+          echo "# 📦 GitHub Releases" >> "$GITHUB_STEP_SUMMARY"
+        fi
+
+        # Run and capture GitHub CLI Command
+        if [ "$RETURN_TYPE" = "test" ]; then
+          # Text output is actually a JSON query processed with fixed arguments
+          echo "Running: $GH_CLI $CLI_FLAGS"
+          RELEASE_OUTPUT=$($GH_CLI $CLI_FLAGS --json tagName -q '.[] | .tagName')
+        else
+          echo "Running: $GH_CLI $CLI_FLAGS"
+          RELEASE_OUTPUT=$($GH_CLI $CLI_FLAGS")
+        fi
+
+        # Check with leading character in place
+        checkReleases
+
+        if [ "$MATCH" != "true" ]; then
+          if [[ "$TAG" == v* ]]; then
+            TAG="${TAG:1}"
+            # Check again with leading 'v' character stripped
+            echo "Checking tag input with leading character stripped"
+            checkReleases
+          fi
+        fi
+
+        if [ "$MATCH" = "true" ]; then
+          echo "Release has already been published: $TAG ⚠️"
+        else
+          echo "Release has NOT been published yet: $TAG ✅"
+        fi
+        if [ "f$SUMMARY_OUTPUT" = "ftrue" ]; then
+          if [ "$MATCH" = "true" ]; then
+            echo "Release has already been published: $TAG ⚠️" >> "$GITHUB_STEP_SUMMARY"
+          else
+            echo "Release has NOT been published yet: $TAG ✅" >> "$GITHUB_STEP_SUMMARY"
+          fi
+        fi
