Feat: Update Python project name enumeration steps (#577)
Also adds documentation/README.md files and updates tests.

Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/python-project-name-action/action.yaml b/.github/actions/python-project-name-action/action.yaml
--- a/.github/actions/python-project-name-action/action.yaml
+++ b/.github/actions/python-project-name-action/action.yaml
@@ -3,18 +3,23 @@
 # SPDX-FileCopyrightText: 2024 The Linux Foundation
 
 # python-project-name-action
-name: "🐍 Get Python Project Name"
-description: "Returns the name of the Python Project"
-# Retrieves from either pyproject.toml or setup.py
+name: "🐍 Python Project/Package Names"
+description: "Extracts Python project name and derives the package name"
+# Uses project description from pyproject.toml or setup.py
 
 outputs:
+  # Mandatory
+  PYTHON_PROJECT_FILE:
+    # Note: dashes in the name are substituted with underscores
+    description: "File used to extract project metadata [pyproject.toml|setup.py]"
+    value: ${{ steps.capture.outputs.python_project_file }}
   PYTHON_PROJECT_NAME:
-    description: "The name of the Python project from pyproject.toml or setup.py"
-    value: ${{ steps.variables.outputs.python_project_name }}
-  PYTHON_BUILD_NAME:
-    # Any dashes in the name will be replaced with underscores
-    description: "The name of the Python project when built"
-    value: ${{ steps.variables.outputs.python_build_name }}
+    description: "Name of the Python project from pyproject.toml/setup.py"
+    value: ${{ steps.capture.outputs.python_project_name }}
+  PYTHON_PACKAGE_NAME:
+    # Note: dashes in the name are substituted with underscores
+    description: "The name of the Python package"
+    value: ${{ steps.capture.outputs.python_package_name }}
 
 runs:
   using: "composite"
@@ -25,13 +30,7 @@ runs:
       with:
         path: "setup.py"
 
-    # yamllint disable-line rule:line-length
-    - uses: lfit/releng-reusable-workflows/.github/actions/path-check-action@11530dee75e77f063c6e01ac7f3a6cb0cdc95db7 # 2025-02-05
-      id: pyproject-toml
-      with:
-        path: "pyproject.toml"
-
-    - name: "Use project name from setup.py"
+    - name: "Get project name from setup.py"
       id: setup-py-name
       if: steps.setup-py.outputs.type == 'file'
       # yamllint disable-line rule:line-length
@@ -41,7 +40,13 @@ runs:
         regex: '(?<=name=")([^"]*)'
         filename: "setup.py"
 
-    - name: "Use project name from pyproject.toml"
+    # yamllint disable-line rule:line-length
+    - uses: lfit/releng-reusable-workflows/.github/actions/path-check-action@11530dee75e77f063c6e01ac7f3a6cb0cdc95db7 # 2025-02-05
+      id: pyproject-toml
+      with:
+        path: "pyproject.toml"
+
+    - name: "Get project name from pyproject.toml"
       id: pyproject-toml-name
       if: steps.pyproject-toml.outputs.type == 'file'
       # yamllint disable-line rule:line-length
@@ -51,42 +56,52 @@ runs:
         regex: '(?<=^name = ")([^"]*)'
         filename: "pyproject.toml"
 
-    - name: "Throw error if Python project metadata was NOT found"
-      if: steps.pyproject-toml.outputs.type == 'invalid' &&
-        steps.setup-py.outputs.type == 'invalid'
+    - name: "Capture Python project metadata"
+      if: env.python_project != 'false'
+      id: capture
       shell: bash
       run: |
-        # Throw error if Python project metadata was NOT found
-        echo "Neither pyproject.toml NOR setup.py were found"; exit 1
-
-    - name: "Return extracted values"
-      id: variables
-      shell: bash
-      run: |
-        # Return extracted values
+        # Capture Python project metadata
 
         # pyproject.toml is preferred source if both files exist
         if [ ${{ steps.pyproject-toml.outputs.type == 'file' }} ]; then
-          echo "Using project name from source: pyproject.toml"
+          echo "Using project name from: pyproject.toml"
           PYTHON_PROJECT_NAME="${{ steps.pyproject-toml-name.outputs.extracted_string}}"
+          PYTHON_PROJECT_FILE="pyproject.toml"
 
         elif [ ${{ steps.setup-py.outputs.type == 'file' }} ]; then
-          echo "Using project name from source: setup.py"
+
+          # This is a legacy format and does not conform to the latest PEP standards
+
+          echo "Using project name from: setup.py"
           PYTHON_PROJECT_NAME="${{ steps.setup-py-name.outputs.extracted_string}}"
+          PYTHON_PROJECT_FILE="setup.py"
+
+          # Project is defined using legacy standards
+          echo "# ⚠️ Project using outdated format: setup.py"
+          echo "This Python project format is deprecated"
+          echo "The repository content needs updating"
+
+          echo "# ⚠️ Project using outdated format: setup.py" >> "$GITHUB_STEP_SUMMARY"
+          echo "This Python project format is deprecated" >> "$GITHUB_STEP_SUMMARY"
+          echo "The repository content needs updating" >> "$GITHUB_STEP_SUMMARY"
         fi
 
         if [ -z "$PYTHON_PROJECT_NAME" ]; then
-          echo "The project name extraction failed ❌"; exit 1
+          echo "Python project name extraction failed ❌"
+          exit 1
         fi
 
-        echo "python_project_name: $PYTHON_PROJECT_NAME ✅"
+        echo "Python project name: $PYTHON_PROJECT_NAME ✅"
 
         # Replace all dashes in the name with underscores
-        PYTHON_BUILD_NAME=$(echo "$PYTHON_PROJECT_NAME" | tr '-' '_')
-        echo "python_build_name: $PYTHON_BUILD_NAME"
+        PYTHON_PACKAGE_NAME=$(echo "$PYTHON_PROJECT_NAME" | tr '-' '_')
+        echo "Python package name: $PYTHON_PACKAGE_NAME"
 
         # Make available to the GitHub environment
         echo "python_project_name=$PYTHON_PROJECT_NAME" >> "$GITHUB_ENV"
         echo "python_project_name=$PYTHON_PROJECT_NAME" >> "$GITHUB_OUTPUT"
-        echo "python_build_name=$PYTHON_BUILD_NAME" >> "$GITHUB_ENV"
-        echo "python_build_name=$PYTHON_BUILD_NAME" >> "$GITHUB_OUTPUT"
+        echo "python_package_name=$PYTHON_PACKAGE_NAME" >> "$GITHUB_ENV"
+        echo "python_package_name=$PYTHON_PACKAGE_NAME" >> "$GITHUB_OUTPUT"
+        echo "python_project_file=$PYTHON_PROJECT_FILE" >> "$GITHUB_ENV"
+        echo "python_project_file=$PYTHON_PROJECT_FILE" >> "$GITHUB_OUTPUT"
diff --git a/.github/workflows/merge-test-gha.yaml b/.github/workflows/merge-test-gha.yaml
--- a/.github/workflows/merge-test-gha.yaml
+++ b/.github/workflows/merge-test-gha.yaml
@@ -85,6 +85,45 @@ jobs:
           else
             echo "Returned project name is correct: $PYTHON_PROJECT_NAME"
           fi
+          PYTHON_PROJECT_NAME="${{ steps.python-project-name-action.outputs.python_package_name }}"
+          if [ "$PYTHON_PACKAGE_NAME" != "osc_github_devops" ]; then
+            echo "ERROR: Python package name was not as expected"
+            echo "python_package_name: $PYTHON_PROJECT_NAME"; exit 1
+          else
+            echo "Returned package name is correct: $PYTHON_PROJECT_NAME"
+          fi
+          PYTHON_PROJECT_FILE="${{ steps.python-project-name-action.outputs.python_project_file }}"
+          if [ "$PYTHON_PROJECT_FILE" != "pyproject.toml" ]; then
+            echo "ERROR: Python project file was not as expected"
+            echo "python_project_file: $PYTHON_PROJECT_FILE"; exit 1
+          else
+            echo "Returned Python project file is correct: $PYTHON_PROJECT_FILE"
+          fi
+
+      # Note: project-name-action depends on action above (python-project-name-action)
+      - name: "Action: project-name-action"
+        id: project-name-action
+        # yamllint disable-line rule:line-length
+        uses: os-climate/osc-github-devops/.github/actions/project-name-action@main
+
+      - name: "Validate: project-name-action"
+        shell: bash
+        run: |
+          # Check output from: project-name-action
+          PROJECT_NAME="${{ steps.project-name-action.outputs.project_name }}"
+          if [ "$PROJECT_NAME" != "osc-github-devops" ]; then
+            echo "ERROR: Python project name was not as expected"
+            echo "project_name: $PROJECT_NAME"; exit 1
+          else
+            echo "Returned project name is correct: $PROJECT_NAME"
+          fi
+          MATCH="${{ steps.project-name-action.outputs.match }}"
+          if [ "$MATCH" != "true" ]; then
+            echo "ERROR: Flag NOT set indicating project and repository name match"
+            exit 1
+          else
+            echo "Flag set indicating project and repository name match"
+          fi
 
       - name: "Action: python-project-version-action"
         id: python-project
@@ -101,24 +140,6 @@ jobs:
             echo "python_project_version: $PYTHON_PROJECT_VERSION"; exit 1
           else
             echo "Returned project version is correct: $PYTHON_PROJECT_NAME"
-          fi
-
-      - name: "Action: project-name-compare-action"
-        id: project-name-compare-action
-        # yamllint disable-line rule:line-length
-        uses: os-climate/osc-github-devops/.github/actions/project-name-compare-action@main
-
-      - name: "Validate: project-name-compare-action"
-        shell: bash
-        run: |
-          # Check output from: project-name-compare-action
-          MATCHES_REPO_NAME="${{ steps.project-name-compare-action.outputs.MATCHES_REPO_NAME }}"
-          if [ "$MATCHES_REPO_NAME" != "true" ]; then
-            echo "ERROR: Python project name did not match repository name, as expected"
-            echo "MATCHES_REPO_NAME: $MATCHES_REPO_NAME"; exit 1
-          else
-            echo "Project name matched repository name, as expected"
-            echo "MATCHES_REPO_NAME: $MATCHES_REPO_NAME"
           fi
 
       - name: "Extract TOX stanza"
