Feat: Implement/update multi-line string matching
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/string-in-multiline-text-action/action.yaml b/.github/actions/string-in-multiline-text-action/action.yaml
--- a/.github/actions/string-in-multiline-text-action/action.yaml
+++ b/.github/actions/string-in-multiline-text-action/action.yaml
@@ -9,7 +9,7 @@ inputs:
   STRING:
     description: "String/line to match"
     required: true
-  ENCODED_TEXT:
+  MULTILINE_TEXT:
     description: "Text to search for match"
     required: true
   SUBSTRING_MATCH:
@@ -17,6 +17,10 @@ inputs:
     required: false
     default: "false"
   CASE_INSENSITIVE:
+    required: false
+    default: "false"
+  BASE64_ENCODED:
+    description: "Set true if multiline text is base64 encoded"
     required: false
     default: "false"
 
@@ -38,6 +42,7 @@ runs:
       env:
         SUBSTRING_MATCH: ${{ inputs.SUBSTRING_MATCH }}
         CASE_INSENSITIVE: ${{ inputs.CASE_INSENSITIVE }}
+        BASE64_ENCODED: ${{ inputs.BASE64_ENCODED }}
       run: |
         # Perform comparison of string values
 
@@ -49,17 +54,18 @@ runs:
           export GITHUB_OUTPUT="/dev/null"
           export GITHUB_ENV="/dev/null"
           if [ $# -ne 4 ]; then
-            echo "Usage:  $0 [string] [base64 text] [match substring true|false] [case-insensitive true|false]"
+            echo "Usage:  $0 [string] [text] [substring] [case-insensitive] [base64-encoded]"
             echo "Error: invalid arguments specified"; exit 1
           else
             STRING="$1"
-            ENCODED_TEXT="$2"
+            MULTILINE_TEXT="$2"
             SUBSTRING_MATCH="$3"
             CASE_INSENSITIVE="$4"
+            BASE64_ENCODED="$5"
           fi
         else
           STRING="${{ inputs.STRING }}"
-          ENCODED_TEXT="${{ inputs.ENCODED_TEXT }}"
+          MULTILINE_TEXT="${{ inputs.MULTILINE_TEXT }}"
           SUBSTRING_MATCH="${{ inputs.SUBSTRING_MATCH }}"
           CASE_INSENSITIVE="${{ inputs.CASE_INSENSITIVE }}"
         fi
@@ -70,20 +76,28 @@ runs:
         if [ "$CASE_INSENSITIVE" != "true" ] && [ "$CASE_INSENSITIVE" != "false" ]; then
           echo "Error: case-insentivive match argument != [true|false]"; exit 1
         fi
+        if [ "$BASE64_ENCODED" != "true" ] && [ "$BASE64_ENCODED" != "false" ]; then
+          echo "Error: base64-encoded match argument != [true|false]"; exit 1
+        fi
 
         COUNT="0"
 
         if [ "$CASE_INSENSITIVE" = "true" ]; then
-          echo "Case-insensitive string comparison requested"
+          echo "Case-insensitive string comparison requested ℹ️"
           shopt -s nocasematch
         fi
 
-        echo "String to match: $STRING"
-        echo "Multi-line base64 encoded text:"
-        echo "$ENCODED_TEXT"
+        if [ "$BASE64_ENCODED" = "true" ]; then
+          echo "Text is base64 encoded 🔑"
+          echo "$MULTILINE_TEXT"
+          TEXT=$(base64 -d <<< "$MULTILINE_TEXT")
+        else
+          TEXT="$MULTILINE_TEXT"
+        fi
 
-        TEXT=$(base64 -d <<< "$ENCODED_TEXT")
-        echo "Decoded text:"
+        echo "String to match 🔤"
+        echo "$STRING"
+        echo "Multiline text 📚"
         echo "$TEXT"
 
         MATCH="false"
