Feat: Add summary step output when dev tag pushed (#1028)
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/build-test-release.yaml b/.github/workflows/build-test-release.yaml
--- a/.github/workflows/build-test-release.yaml
+++ b/.github/workflows/build-test-release.yaml
@@ -42,7 +42,10 @@ jobs:
         shell: bash
         run: |
           # Reject Development Tags
-          echo "Development tag pushed; aborting release workflow 🛑"; exit 1
+          echo "Development tag pushed; aborting release workflow 🛑"
+          echo "Development tag pushed; aborting release workflow 🛑" \
+            >> "$GITHUB_STEP_SUMMARY"
+          exit 1
 
   python-build:
     name: 'Python Build'
