Feat: Reject development tags in release workflow
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/build-test-release.yaml b/.github/workflows/build-test-release.yaml
--- a/.github/workflows/build-test-release.yaml
+++ b/.github/workflows/build-test-release.yaml
@@ -37,6 +37,13 @@ jobs:
         with:
           versioning: 'semver'
 
+      - name: 'Reject Development Tags'
+        if: steps.tag-validate.outputs.dev_version == 'true'
+        shell: bash
+        run: |
+          # Reject Development Tags
+          echo "Development tag pushed; aborting release workflow 🛑"; exit 1
+
   python-build:
     name: 'Python Build'
     needs: 'tag-validate'
