Feat: Major updates to 1Password workflow (#91)
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/one-password-credentials.yaml b/.github/workflows/one-password-credentials.yaml
--- a/.github/workflows/one-password-credentials.yaml
+++ b/.github/workflows/one-password-credentials.yaml
@@ -2,43 +2,113 @@
 # SPDX-License-Identifier: Apache-2.0
 # SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>
 
+# 1Password Service
 name: "🔑 [R] 1Password"
-# Tests access to 1Password is available using a sample secure note
 
 on:
   workflow_call:
     inputs:
+      # Required inputs
       VAULT_ITEM:
         description: "Element to load from 1Password using service account"
-        required: true
+        required: false
         type: string
+      # Optional inputs
+      ACCESS_TYPE:
+        description: "Descriptive label for vault access, e.g. [both|development|production|none]"
+        required: false
+        type: string
+        default: "none"
       EXPORT:
-        description: "Whether to export element into environment (subsequent steps)"
+        description: "Export vault element to environment/subsequent steps"
         required: false
         default: false
         type: boolean
+
+    # Service account credentials
     secrets:
-      OP_SERVICE_ACCOUNT_TOKEN:
-        description: "1Password service account credential"
-        required: true
+      ONE_PASSWORD_DEVELOPMENT:
+        description: "1Password service account [Development]"
+        required: false
+      ONE_PASSWORD_PRODUCTION:
+        description: "1Password service account [Development]"
+        required: false
 
 jobs:
   one-password-access:
     name: "Test Availability"
     runs-on: "ubuntu-latest"
     steps:
-      - name: "Load element from 1Password Vault"
+      # This is necessary, as most inputs are NOT mandatory
+      # However, we do NOT want this workflow to fail/block others
+      - name: "Validate 1Password workflow inputs"
+        run: |
+          # Validate 1Password workflow inputs
+          if [ -z ${{ inputs.vault_item }} ] && [ ${{ inputs.access_type }} != 'none' ]; then
+            echo "Error: vault item is required unless access_type is set to none"
+            ERRORS='true'
+          fi
+          if [ -z ${{ secrets.one_password_development }} ] && \
+          { [ ${{ inputs.access_type }} = 'development' ] || [ ${{ inputs.access_type }} = 'both' ]; }; then
+            echo "Missing credential: 1Password Service Account [Development]"
+            ERRORS='true'
+          fi
+          if [ -z ${{ secrets.one_password_production }} ] && \
+          { [ ${{ inputs.access_type }} = 'production' ] || [ ${{ inputs.access_type }} = 'both' ]; }; then
+            echo "Missing credential: 1Password Service Account [Production]"
+            ERRORS='true'
+          fi
+          if [ "$ERRORS" ]; then
+            echo "Check workflow inputs/parameters"
+            exit 1
+          fi
+
+      - name: "1Password Service Account [Development]"
         uses: 1password/load-secrets-action@v2
+        if: inputs.ACCESS_TYPE == 'development' || inputs.ACCESS_TYPE == 'both'
         with:
           # Export loaded secrets as environment variables
-          export-env: ${{ inputs.EXPORT }}
+          export-env: ${{ inputs.export }}
         env:
-          VAULT_ITEM: ${{ inputs.VAULT_ITEM }}
-          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
+          VAULT_ITEM: ${{ inputs.vault_item }}
+          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.one_password_development }}
 
-      - name: "Print masked variables"
-        # Prints: Secret: ***
+      - name: "1Password Service Account [Production]"
+        uses: 1password/load-secrets-action@v2
+        if: inputs.ACCESS_TYPE == 'production' || inputs.ACCESS_TYPE == 'both'
+        with:
+          # Export loaded secrets as environment variables
+          export-env: ${{ inputs.export }}
+        env:
+          VAULT_ITEM: ${{ inputs.vault_item }}
+          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.one_password_production }}
+
+      # Prints masked secret value: ***
+      - name: "Test masked output value"
+        if: inputs.ACCESS_TYPE == 'development' || inputs.ACCESS_TYPE == 'both'
         run: |
-          # Print masked variable
+          # Test masked output value
           echo "Element loaded as variable: $VAULT_ITEM"
-          echo "export-env was set to: ${{ inputs.EXPORT }}"
+          echo "export-env was set to: ${{ inputs.export }}"
+
+      - name: "Print summary to job output"
+        run: |
+          # Print summary to job output
+          # shellcheck disable=SC2129
+
+          echo "# 🔑 1Password Service Access" >> "$GITHUB_STEP_SUMMARY"
+
+          echo "Status of 1Password service account access" >> "$GITHUB_STEP_SUMMARY"
+
+          echo "| Status | Account Type |" >> "$GITHUB_STEP_SUMMARY"
+          echo "| ------ | ---------------------|" >> "$GITHUB_STEP_SUMMARY"
+          if [ -z ${{ secrets.one_password_development }} ]; then
+            echo "| ❌ | Development Service Account |" >> "$GITHUB_STEP_SUMMARY"
+          else
+            echo "| ✅ | Development Service Account |" >> "$GITHUB_STEP_SUMMARY"
+          fi
+          if [ -z ${{ secrets.one_password_production }} ]; then
+            echo "| ❌ | Production Service Account |" >> "$GITHUB_STEP_SUMMARY"
+          else
+            echo "| ✅ | Production Service Account |" >> "$GITHUB_STEP_SUMMARY"
+          fi
