Chore: Rename workflow
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/one-password.yaml b/.github/workflows/one-password.yaml
--- a/.github/workflows/one-password.yaml
+++ b/.github/workflows/one-password.yaml
@@ -35,8 +35,8 @@ on:
         required: false
 
 jobs:
-  one-password-access:
-    name: "Test Availability"
+  one-password:
+    name: "Access Vaulted Credentials"
     runs-on: "ubuntu-latest"
     steps:
       - name: "Validate 1Password workflow inputs"
@@ -46,7 +46,8 @@ jobs:
         run: |
           # Validate 1Password workflow inputs
           if [ -z "${{ inputs.vault_item }}" ] && [ "${{ inputs.access_type }}" != 'none' ]; then
-            echo "Error: vault item is required unless access_type is set to none"; exit 1
+            echo "Error: vault item is required unless access_type set to none"
+            exit 1
           fi
 
       - name: "1Password Service Account [Development]"
@@ -71,7 +72,7 @@ jobs:
 
       # Prints masked secret value: ***
       - name: "Test masked output value"
-        if: inputs.ACCESS_TYPE == 'development' || inputs.ACCESS_TYPE == 'both'
+        if: inputs.ACCESS_TYPE == 'development'
         run: |
           # Test masked output value
           echo "Element loaded as variable: $VAULT_ITEM"
@@ -82,18 +83,18 @@ jobs:
           # Print summary to job output
           # shellcheck disable=SC2129
 
-          echo "# 🔑 1Password" >> "$GITHUB_STEP_SUMMARY"
+          echo "# 🔑 1Password Service Access" >> "$GITHUB_STEP_SUMMARY"
 
-          echo "## Service Account Availability" >> "$GITHUB_STEP_SUMMARY"
+          echo "## Availability of credentials and service accounts to this workflow run" >> "$GITHUB_STEP_SUMMARY"
 
           echo "| Status | Account Type |" >> "$GITHUB_STEP_SUMMARY"
           echo "| ------ | ---------------------|" >> "$GITHUB_STEP_SUMMARY"
-          if [ -z ${{ secrets.one_password_development }} ]; then
+          if [ -z "${{ secrets.one_password_development }}" ]; then
             echo "| ❌ | Development Service Account |" >> "$GITHUB_STEP_SUMMARY"
           else
             echo "| ✅ | Development Service Account |" >> "$GITHUB_STEP_SUMMARY"
           fi
-          if [ -z ${{ secrets.one_password_production }} ]; then
+          if [ -z "${{ secrets.one_password_production }}" ]; then
             echo "| ❌ | Production Service Account |" >> "$GITHUB_STEP_SUMMARY"
           else
             echo "| ✅ | Production Service Account |" >> "$GITHUB_STEP_SUMMARY"
