Fix: Quoted variables in complex conditionals
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/one-password-credentials.yaml b/.github/workflows/one-password-credentials.yaml
--- a/.github/workflows/one-password-credentials.yaml
+++ b/.github/workflows/one-password-credentials.yaml
@@ -39,28 +39,14 @@ jobs:
     name: "Test Availability"
     runs-on: "ubuntu-latest"
     steps:
-      # This is necessary, as most inputs are NOT mandatory
-      # However, we do NOT want this workflow to fail/block others
       - name: "Validate 1Password workflow inputs"
+        # This is necessary, as most inputs are NOT mandatory
+        # However, we do NOT want this workflow to fail/block others
+        shell: bash
         run: |
           # Validate 1Password workflow inputs
-          if [ -z ${{ inputs.vault_item }} ] && [ ${{ inputs.access_type }} != 'none' ]; then
-            echo "Error: vault item is required unless access_type is set to none"
-            ERRORS='true'
-          fi
-          if [ -z ${{ secrets.one_password_development }} ] && \
-          { [ ${{ inputs.access_type }} = 'development' ] || [ ${{ inputs.access_type }} = 'both' ]; }; then
-            echo "Missing credential: 1Password Service Account [Development]"
-            ERRORS='true'
-          fi
-          if [ -z ${{ secrets.one_password_production }} ] && \
-          { [ ${{ inputs.access_type }} = 'production' ] || [ ${{ inputs.access_type }} = 'both' ]; }; then
-            echo "Missing credential: 1Password Service Account [Production]"
-            ERRORS='true'
-          fi
-          if [ "$ERRORS" ]; then
-            echo "Check workflow inputs/parameters"
-            exit 1
+          if [ -z "${{ inputs.vault_item }}" ] && [ "${{ inputs.access_type }}" != 'none' ]; then
+            echo "Error: vault item is required unless access_type is set to none"; exit 1
           fi
 
       - name: "1Password Service Account [Development]"
